version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=projeto_jpa
    ports:
      - "3306:3306"
  maven:
      build:
        context: .
        dockerfile: Dockerfile-maven
      volumes:
        - ~/.m2:/root/.m2
        - .:/usr/src/mymaven
      volumes_from:
        - tomcat
      entrypoint:
        - ./entrypointscript.sh
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile-apache
    ports:
      - "8888:8080"
  #volume:
    #$CATALINA_HOME/webapps/
